n=input("Enter text to write to the file: ")
file=open("output.txt","w")
file.write(n)
file.close()
print("Date succesfully written to output.txt")
n1=input("Enter additional text to append:")
file=open("output.txt","a")
file.write("\n"+n1)
file.close()
print("Date succesfully appended")
print("Final content of output.txt:")
file=open("output.txt","r")
print(file.read())
file.close()